### ISSUE TITLE
AttributeError: module 'cflearn' has no attribute 'make'

### ISSUE THREAD

**Issue by impulsecorp** [carefree0910/carefree-learn#1]
On my Ubuntu 18.04.4 server, when I run your quick start code, I get this error:
root@server1:~/newautoml# python3 cflearn.py
Traceback (most recent call last):
  File "cflearn.py", line 1, in <module>
    import cflearn
  File "/root/newautoml/cflearn.py", line 5, in <module>
    m = cflearn.make().fit(x, y)
AttributeError: module 'cflearn' has no attribute 'make'

**Comment by carefree0910** [comment]
That's pretty weird... Could you please tell me how did you install `carefree-learn` and what's your python version? Because I've run some CI tests [here](https://github.com/carefree0910/carefree-learn/runs/934346216?check_suite_focus=true) on Ubuntu 18.04.4, which did not raise errors (the usage of `cflearn.make` is included [here](https://github.com/carefree0910/carefree-learn/blob/dev/tests/usages/test_basic.py#L15))

**Comment by impulsecorp** [comment]
I installed it using:  sudo pip3 install carefree-learn
I am running Python 3.6.9
My cflearn.py file is:
import cflearn
from cfdata.tabular import TabularDataset

x, y = TabularDataset.iris().xy
m = cflearn.make().fit(x, y)
# Make label predictions
m.predict(x)
# Make probability predictions
m.predict_prob(x)
# Estimate performance
cflearn.estimate(x, y, wrappers=m)

**Comment by carefree0910** [comment]
I've created a new conda env with python==3.6.9 on Ubuntu 18.04.4, installed PyTorch, `pip install carefree-learn`, and everything is working fine for me 😭

It might be helpful if you know where your python site-packages are and check whether there are something like `def make` in `site-packages/cflearn/__init__.py`; if not, then perhaps something went wrong with your python environment 😢

**Comment by carefree0910** [comment]
Ok, I finally realized that your file is named `cflearn`, so when you are trying to `import cflearn`, Python will import your current file, not `carefree-learn`! 🤣

Simply rename your file and everything should be OK 😁

**Comment by impulsecorp** [comment]
Yes, I renamed it and it works now. Thanks!

**Comment by carefree0910** [comment]
You're welcome! 😄
