### ISSUE TITLE
AttributeError: module 'cflearn' has no attribute 'Auto'

### ISSUE THREAD

**Issue by Vaunorage** [carefree0910/carefree-learn#10]
when running turorial code :

```
import cflearn

from cfdata.tabular import *

# prepare iris dataset
iris = TabularDataset.iris()
iris = TabularData.from_dataset(iris)
# split 10% of the data as validation data
split = iris.split(0.1)
train, valid = split.remained, split.split
x_tr, y_tr = train.processed.xy
x_cv, y_cv = valid.processed.xy
data = x_tr, y_tr, x_cv, y_cv

#%%
fcnn = cflearn.make().fit(*data)

# 'overfit' validation set
auto = cflearn.Auto(TaskTypes.CLASSIFICATION).fit(*data, num_jobs=2)

# estimate manually
predictions = auto.predict(x_cv)
print("accuracy:", (y_cv == predictions).mean())

# estimate with `cflearn`
cflearn.estimate(
    x_cv,
    y_cv,
    pipelines=fcnn,
    other_patterns={"auto": auto.pattern},
)
```

Get this error :

  File "C:\ProgramData\miniconda\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-c5cf3842387c>", line 4, in <module>
    auto = cflearn.Auto(TaskTypes.CLASSIFICATION).fit(*data, num_jobs=2)
AttributeError: module 'cflearn' has no attribute 'Auto'

**Comment by carefree0910** [comment]
Hi! It's my bad for not clarifying that the `AutoML` usage is only available through pip installing from source 😢 I'll update the `README.md` ASAP!

**Comment by carefree0910** [comment]
I've updated the `README.md`, hiding oridinary `pip install` method 😅

I know this is something bad but I'm busy working on new features, after which I'll release a new version! 🤣
