### ISSUE TITLE
AutoML Scores

### ISSUE THREAD

**Issue by impulsecorp** [carefree0910/carefree-learn#9]
The scores in your Titanic demo, with the new AutoML system, are not as good as they were before. I tried it now using https://github.com/carefree0910/carefree-learn/blob/dev/examples/titanic/test_titanic.py
and submitted to Kaggle and got: 
Optuna: 0.77751
HPO - 0.75598 
AdaBoost: 0.67703

**Comment by impulsecorp** [comment]
I also ran it on a much larger, private dataset (stock data), and it got .5310 vs .5300 a week ago, so that is good, although that difference could be due to variance.  It still worries me though the AutoML version was lower for Titanic.

**Comment by carefree0910** [comment]
Thank you very much for your testing! Currently the AutoML system is still WIP so the performance might not be stable. I'm still working hard on implementing some basic features, after which I'll dig into the performance part. Once I thought everything is ready, I'll release a `v0.1.3` version! 😉

> I'll leave this issue open until I fix things up 🤣

**Comment by carefree0910** [comment]
> The scores in your Titanic demo, with the new AutoML system, are not as good as they were before. I tried it now using https://github.com/carefree0910/carefree-learn/blob/dev/examples/titanic/test_titanic.py
> and submitted to Kaggle and got:
> Optuna: 0.77751
> HPO - 0.75598
> AdaBoost: 0.67703

BTW currently the default settings in titanic demo is nowhere near good, because I've made some changes to accelerate the CI process which would dramatically hurt the performance. I've introduced a `CI` flag in `test_titanic.py` and the results should be much better with `CI = False` 😄

> However I believe you've already set it to `False`, so I'm leaving this comment in case other users face the same problem😉

**Comment by carefree0910** [comment]
FYI, I had done some experiments and could not get satisfying results **stably** (I still managed to get a 0.806 result though, maybe by accident 🤣) until I found out [this issue](https://github.com/optuna/optuna/pull/1927#issue-503046190) I fixed for `optuna` actually hurts the HPO performance quite a lot 😢

After fixing this `optuna` issue on my local machine, on current `dev` branch I ran through `./examples/titanic/automl.py` several times, and got ~0.79, somtimes >0.80 **quite stably** 😆

So maybe I'll not be confident enough to inform you that `carefree-learn` is ready until `optuna` releases their `v2.3.0` version 😉

**Comment by impulsecorp** [comment]
Great, I will try it again.

**Comment by carefree0910** [comment]
> Great, I will try it again.

Just in case: in order to reproduce the result, maybe you'll need to make the same changes on your own machine(s) to `optuna` as I've done [here](https://github.com/optuna/optuna/pull/1927#issue-503046190) 😉

**Comment by impulsecorp** [comment]
Thanks, that fixed it!  
I upgraded to your newest version now, but did not edit Optuna (but I did upgrade to the latest version of it), and ./examples/titanic/automl.py scored 0.79904 on Kaggle.
